### ISSUE TITLE
Mispelling

### ISSUE THREAD

**Issue by Grabou** [Juuroku/DeepL-Tool-Firefox-Addon-#1]
Thank you for this extension!

But it's Fr**e**nch. ;)

![image](https://user-images.githubusercontent.com/33343310/221188434-437f69fb-294f-4517-82fe-9cf0e8201605.png)

**Comment by Juuroku** [comment]
Sorry for the misspelling, I'll fix it as soon as possible.
Also really thank you for the report.

**Comment by Grabou** [comment]
Oh, I think I just found a bug.

### I'm on Firefox 111.0b5 (64 bits).

Even if I select "French" in the Target Lang option, this is "German" which is selected (the first language available in the list).

![230224-142303-firefox](https://user-images.githubusercontent.com/33343310/221189763-307355cc-d944-4877-8819-2c376f4094d8.png)

![image](https://user-images.githubusercontent.com/33343310/221189645-a888014f-5c0a-4117-a7e5-9d72560a8f0a.png)

Thank you!

**Comment by Juuroku** [comment]
@Grabou 
The configuration in options page is for the in-page translate function which use the api key, and the pop-up window will remember what your have chosen last time.
May be I will add some descriptions in the options, still appreciate your response!

**Comment by Grabou** [comment]
Oh sorry! Good, thanks. :)

**Comment by Juuroku** [comment]
@Grabou 
It's fine!
I'm really happy to know either bugs or designing problems!

**Comment by Grabou** [comment]
OK. So if you want some design suggestions, it would be nice if the DeepL translation launched in a new tab as soon as you clicked on **DeepL Tool > Send to DeepL Tool**, rather than having to validate the highlighted text in the extension box by clicking on **Translate**.

The **From Clipboard** button seems pretty useless as the DeepL Tool menu (right click) doesn't show up without having highlighted text.

Maybe we could have two choices in the right click after highlighting the text:
- Send to DeepL Tool (direct)
- Send to DeepL Tool (with a pit-stop through the dialog box to check the parameters)

I don't know if I'm clear or if it's doable. :)

**Comment by Juuroku** [comment]
Thank you for the suggestions.
I will consider to add an option to context menu and let user to active a tab directly.

The 'From Clipboard' button is for someone like me who don't active extensions in the private browsing or use browser while doing other things. :)

**Comment by Juuroku** [comment]
@Grabou 
I've fix the misspelling of 'French' in the latest release of the extension, please update it from `about:addons` page if it does not update automatically.
I will close this issue and move the feature request to another issue, thank you for the report. :)
