### ISSUE TITLE
Add New Option to Context Menu to Activate New Tab Directly

### ISSUE THREAD

**Issue by Juuroku** [Juuroku/DeepL-Tool-Firefox-Addon-#2]
> OK. So if you want some design suggestions, it would be nice if the DeepL translation launched in a new tab as soon as you clicked on **DeepL Tool > Send to DeepL Tool**, rather than having to validate the highlighted text in the extension box by clicking on **Translate**.
> 
> The **From Clipboard** button seems pretty useless as the DeepL Tool menu (right click) doesn't show up without having highlighted text.
> 
> Maybe we could have two choices in the right click after highlighting the text:
>  - Send to DeepL Tool (direct)
>  - Send to DeepL Tool (with a pit-stop through the dialog box to check the parameters)
> 
> I don't know if I'm clear or if it's doable. :)

_Originally posted by @Grabou in https://github.com/Juuroku/DeepL-Tool-Firefox-Addon-/issues/1#issuecomment-1443707858_

**Comment by Juuroku** [comment]
The release v1.2 (66c0d54) contains an update about adding a new context menu to directly open tab to DeepL.
If there are no any questions or requests about the issue, I will close it in about a week.

**Comment by Grabou** [comment]
So cool! Thanks.

But it's not working on my computer (Win 11, FF 111.0b7). Nothing happens.

I tried on a FF private browser session (with only one extension activated) and on my regular FF session. I tried to highlight only text or text + links: same behavior.

What do you need to debug? 🙏

**Comment by Juuroku** [comment]
@Grabou 
Since I use `zh_TW` UI, the screenshots may be different to yours, but the items should be in the same positions.

First, go to the options of the add-on (should be in `about:addons` page).
Switch to details (first tab) and see if the add-on has updated to `v1.2`.
If not, check update (gear icon in the upper right corner)
![detail page](https://user-images.githubusercontent.com/22850368/222594831-2dd81d1c-a9bd-44b8-b6a8-d98769ac2c61.png)

If the add-on is updated, highlight some text and see if there are three items in context menu.
![context menu](https://user-images.githubusercontent.com/22850368/222595551-473bdb27-0ae0-472f-9260-31b87b22db55.PNG)

If there is no third item, or it is not functioning, I will try to reproduce the problem.

Thank you for the report.

**Comment by Grabou** [comment]
Thanks but I obviously checked the plugin version after I saw that nothing was happening. I have v1.2 plugin and I have 3 options in the right click now!

I just tried again on another computer (very similar: W11 + FF 111.0b7) but in another network context (work): same result, nothing happens... 😱

**Comment by Juuroku** [comment]
@Grabou 
So you in your two computers, now first one can work well, and second one still no third option?

Because I don't have a Windows 11 device, it may take a bit to reproduce it, but I'll try.
Really appreciate the report.

**Comment by Juuroku** [comment]
@Grabou
Could you take some screenshots from the options page and context menu?
Also you can go to `about:debugging` page, click the `debug` button to get some console messages.

**Comment by Grabou** [comment]
No. On my two different computers, the behavior is the same with plugin v1.2: the option "Activate DeepL Tab with Selected Text" does nothing. Other options work properly.

For information, I am leaving France tomorrow for one week and will not be available to do tests. ;)

![image](https://user-images.githubusercontent.com/33343310/222731794-5bbd9958-3fa5-4084-9200-335578a8e394.png)

I cant' see "Debug" button on `about:debugging`...

![image](https://user-images.githubusercontent.com/33343310/222732174-a396cd0a-14ee-461b-acbf-fb9543d9d7f4.png)

**Comment by Juuroku** [comment]
The debug button is in the `This Firefox` tab (I think it's `Ce Firefox` in French).
You will see a section of extensions, open it and in each part of every extension should has a `debug` button.
Sorry for the unclear information.

**Comment by Juuroku** [comment]
You can test whenever you're free, really thanks for the information and please do not feel any stress about this.

**Comment by Grabou** [comment]
Ah yes!

I cleaned logs and retried a right click on "Activate DeepL Tab with Selected Text". I got this:

![image](https://user-images.githubusercontent.com/33343310/222734242-f79ec94e-c572-43ec-916c-a685f94ad142.png)

**Comment by Juuroku** [comment]
Thank you for the testing and information, I will try to figure out the problem as soon as possible. 😃

**Comment by Juuroku** [comment]
@Grabou 
I've tried to test in my other computer, and I think the error is caused by unsaved options. (Script can't read the saved options because they do not exist)
To temporary avoid the problem, please go to option page and click submit (no need to change options), and it may work.
I'll add some error handling to the situation in next version.

**Comment by Grabou** [comment]
Haha, you're right, it's working now! 🥳

**Comment by Juuroku** [comment]
The bug is fixed in v1.2.1, please update to the latest version.

**Comment by Juuroku** [comment]
Since there are no reports for over a week, the issue is considered as closed.
